### ISSUE TITLE
Wrong names in README

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/ansible-role-linux-for-postgresql#2]
I believe that some names are wrong in README.md:
* iptables_rules should be iptables.yml?
* optimize_linux should be linux-for-postgresql?

**Comment by mike-aboagye** [comment]
Okay I will take a look at it.

**Comment by mike-aboagye** [comment]
names changed. @federico-razzoli

**Comment by mike-aboagye** [comment]
fixed.
