### ISSUE TITLE
Is replication allowed?

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/ansible-role-linux-for-postgresql#3]
Do WAL-based replication and/or logical replication require more permissive iptables rules? This is a genuine question - I don't know the answer.

**Comment by mike-aboagye** [comment]
Yes replication is allowed. If I make it open instead of setting permissive rules,  any host could connect it.  So the list of ip addresses submitted by the user during iptables settings. Some of them could be used as replicas to the master in production.

**Comment by mike-aboagye** [comment]
fixed.
