### ISSUE TITLE
Don't install PostgreSQL

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/ansible-role-linux-for-postgresql#4]
I believe we should avoid the "Install Postgresql" task. Users can apply this role and THEN apply a PostgreSQL role. Because they could choose a different PostgreSQL version, they could compile it from source, etc.

**Comment by mike-aboagye** [comment]
Okay. I will take it out.

**Comment by mike-aboagye** [comment]
fixed.

**Comment by federico-razzoli** [comment]
I'm reopening because the task is still there.

**Comment by mike-aboagye** [comment]
Tasked removed. Fixed,
