### ISSUE TITLE
Make backup_ipaddress optional

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/ansible-role-linux-for-postgresql#5]
I think iptables will fail if you don't specify backup_ipaddress doesn't exist. I think it should be optional (`when: {{...}} is defined`).

**Comment by mike-aboagye** [comment]
Okay. I will do so.

**Comment by mike-aboagye** [comment]
Issue resolved.

**Comment by mike-aboagye** [comment]
fixed
