### ISSUE TITLE
postgresconn_ipaddress should be a list

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/ansible-role-linux-for-postgresql#6]
In production you don't want to accept connections from a single host. Allow to specify a list (`with_items`).

**Comment by federico-razzoli** [comment]
Maybe it should be empty by default.

**Comment by mike-aboagye** [comment]
Yes empty by default and users could supply list of values to it prior to runtime?

**Comment by federico-razzoli** [comment]
Yes, just a default value

**Comment by mike-aboagye** [comment]
@federico-razzoli  changed it to a list with a set of default values. Is this how you want it to be? Let me know.

**Comment by mike-aboagye** [comment]
Fixed.
